### ISSUE TITLE
Unlinked volumes switch not showing under Settings_Audio

### ISSUE THREAD

**Issue by WTFrancyss** [CherishOS/android_frameworks_base#1]
https://github.com/CherishOS/android_frameworks_base/commit/047204ca646f9ea6907d99b6ea906545faf9765b

**Comment by zahidmgsk** [comment]
> [047204c](https://github.com/CherishOS/android_frameworks_base/commit/047204ca646f9ea6907d99b6ea906545faf9765b)

Please close this issue if resolved @WTFrancyss

**Comment by WTFrancyss** [comment]
Yeah it's fixed, thanks.
