### ISSUE TITLE
Build Error Oneplus 6 Enchilada 

### ISSUE THREAD

**Issue by zahidmgsk** [CherishOS/android_frameworks_base#4]
Build error for Oneplus 6 Enchilada 

[ 86% 9448/10889] //frameworks/base/services/core:services.core.unboosted javac [common]
FAILED: /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar
rm -rf "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && mkdir -p "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes" "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno" "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars" && /mnt/volume_nyc3_01/chandu/ccc/out/soong/host/linux-x86/bin/zipsync -d /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars -l /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list -f "*.java" /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.protologsrc/gen/services.core.protolog.srcjar /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/xsd/platform-compat-config/gen/java/com_android_server_compat_config_xsdcgen.srcjar /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/xsd/display-device-config/gen/java/com_android_server_display_config_xsdcgen.srcjar /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/gen/aidl/aidl0.srcjar && (if [ -s /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list ] || [ -s /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp ] ; then /mnt/volume_nyc3_01/chandu/ccc/out/soong/host/linux-x86/bin/soong_javac_wrapper prebuilts/jdk/jdk11/linux-x86/bin/javac -J-Xmx2048M -J-XX:OnError="cat hs_err_pid%p.log" -J-XX:CICompilerCount=6 -J-XX:+UseDynamicNumberOfGCThreads -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath "" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -processorpath /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/tools/platform-compat/java/android/processor/compat/changeid/compat-changeid-annotation-processor/linux_glibc_common/withres/compat-changeid-annotation-processor.jar -processor android.processor.compat.changeid.ChangeIdProcessor -g:source,lines -Xlint:-dep-ann --system=/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/libcore/mmodules/core_platform_api/core-platform-api-stubs-system-modules/android_common/system -classpath /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/ext/android_common/turbine-combined/ext.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/framework/android_common/turbine-combined/framework.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/net/services.net/android_common/turbine-combined/services.net.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/light/2.0/android.hardware.light-V2.0-java/android_common/turbine-combined/android.hardware.light-V2.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/power/aidl/android.hardware.power-java/android_common/turbine-combined/android.hardware.power-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/power/1.0/android.hardware.power-V1.0-java/android_common/turbine-combined/android.hardware.power-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/vibrator/aidl/android.hardware.vibrator-java/android_common/turbine-combined/android.hardware.vibrator-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/packages/modules/IPsec/android.net.ipsec.ike.stubs.module_lib/android_common/turbine-combined/android.net.ipsec.ike.stubs.module_lib.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/tools/platform-compat/java/android/compat/annotation/app-compat-annotations/android_common/turbine-combined/app-compat-annotations.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/packages/Tethering/common/TetheringLib/framework-tethering.stubs.module_lib/android_common/turbine-combined/framework-tethering.stubs.module_lib.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/apex/permission/service/service-permission.stubs.system_server/android_common/turbine-combined/service-permission.stubs.system_server.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/system/timezone/distro/core/time_zone_distro/android_common/turbine-combined/time_zone_distro.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/system/timezone/distro/installer/time_zone_distro_installer/android_common/turbine-combined/time_zone_distro_installer.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/authsecret/1.0/android.hardware.authsecret-V1.0-java/android_common/turbine-combined/android.hardware.authsecret-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/broadcastradio/2.0/android.hardware.broadcastradio-V2.0-java/android_common/turbine-combined/android.hardware.broadcastradio-V2.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/health/1.0/android.hardware.health-V1.0-java/android_common/turbine-combined/android.hardware.health-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/health/2.0/android.hardware.health-V2.0-java/android_common/turbine-combined/android.hardware.health-V2.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/health/2.1/android.hardware.health-V2.1-java/android_common/turbine-combined/android.hardware.health-V2.1-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/light/aidl/android.hardware.light-java/android_common/turbine-combined/android.hardware.light-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/tv/cec/1.0/android.hardware.tv.cec-V1.0-java/android_common/turbine-combined/android.hardware.tv.cec-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/weaver/1.0/android.hardware.weaver-V1.0-java/android_common/turbine-combined/android.hardware.weaver-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/biometrics/face/1.0/android.hardware.biometrics.face-V1.0-java/android_common/turbine-combined/android.hardware.biometrics.face-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/biometrics/fingerprint/2.2/android.hardware.biometrics.fingerprint-V2.2-java/android_common/turbine-combined/android.hardware.biometrics.fingerprint-V2.2-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/oemlock/1.0/android.hardware.oemlock-V1.0-java/android_common/turbine-combined/android.hardware.oemlock-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/configstore/1.0/android.hardware.configstore-V1.0-java/android_common/turbine-combined/android.hardware.configstore-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/contexthub/1.0/android.hardware.contexthub-V1.0-java/android_common/turbine-combined/android.hardware.contexthub-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/rebootescrow/aidl/android.hardware.rebootescrow-java/android_common/turbine-combined/android.hardware.rebootescrow-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/interfaces/soundtrigger/2.3/android.hardware.soundtrigger-V2.3-java/android_common/turbine-combined/android.hardware.soundtrigger-V2.3-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/system/libhidl/transport/manager/1.2/android.hidl.manager-V1.2-java/android_common/turbine-combined/android.hidl.manager-V1.2-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/av/media/libaudioclient/capture_state_listener-aidl-java/android_common/turbine-combined/capture_state_listener-aidl-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/packages/modules/DnsResolver/dnsresolver_aidl_interface-java/android_common/turbine-combined/dnsresolver_aidl_interface-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/system/netd/server/netd_aidl_interfaces-platform-java/android_common/turbine-combined/netd_aidl_interfaces-platform-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/cmds/idmap2/overlayable_policy_aidl-java/android_common/turbine-combined/overlayable_policy_aidl-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/native/services/surfaceflinger/sysprop/SurfaceFlingerProperties/android_common/turbine-combined/SurfaceFlingerProperties.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/hardware/cherish/interfaces/biometrics/fingerprint/inscreen/1.0/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java/android_common/turbine-combined/vendor.lineage.biometrics.fingerprint.inscreen-V1.0-java.jar:/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/external/motorola/faceunlock/faceunlock_utils/android_common/turbine-combined/faceunlock_utils.jar -source 1.9 -target 1.9 -d /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -s /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/anno @/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar.rsp @/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/list ; fi ) && /mnt/volume_nyc3_01/chandu/ccc/out/soong/host/linux-x86/bin/soong_zip -jar -o /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/services.core.unboosted.jar -C /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes -D /mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/classes && rm -rf "/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars"
/mnt/volume_nyc3_01/chandu/ccc/out/soong/.intermediates/frameworks/base/services/core/services.core.unboosted/android_common/javac/srcjars/frameworks/base/services/core/java/com/android/server/biometrics/AuthenticationClient.java:159: error: cannot find symbol
            if (authenticated && !Utils.isKeyguard(getContext(), getOwnerString())) {
                                       ^
  symbol:   method isKeyguard(Context,String)
  location: class Utils
1 error
11:28:30 ninja failed with: exit status 1

#### failed to build some targets (01:55:23 (hh:mm:ss)) ####

**Comment by zahidmgsk** [comment]
Reason this merge  tag 11.0.0.r27:
[https://github.com/CherishOS/android_frameworks_base/commit/d4621757aff23dae5d44f393feee0045edfc5c1a](url)

**Comment by zahidmgsk** [comment]
Build error resolved by @hungphan2001  - thank you 
https://github.com/CherishOS/android_frameworks_base/commit/ab4186a0f59290453a9cb9ca8af9e7d99c4551b5

**Comment by SALMANKHANPM** [comment]
Nice 👍
