### ISSUE TITLE
FAILED: //frameworks/base/packages/SystemUI:SystemUI-core javac [common]

### ISSUE THREAD

**Issue by bgman111111** [CherishOS/android_frameworks_base#88]
this is from brunch:

https://tefter.bgzashtita.es/?b4be3cb20d672c92#2hC7nKfs2NxuUGqeMfpDSsrbBSYH8QWLvrumdhgvUV9E

and this is from 

out/error.log

https://tefter.bgzashtita.es/?407b9a0483b53b16#B8sm5y1gEtmDf7ogks35q1akHkeHJbeLh56BXPBfNovi

**Comment by hungphan2001** [comment]
I fixed that problem

**Comment by bgman111111** [comment]
when man... then why it still has error.

**Comment by blazey66** [comment]
@bgman111111 resync

**Comment by bgman111111** [comment]
repo sync --force-sync
